-- MySQL Script generated by MySQL Workbench
-- Mon Mar 29 15:18:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdcoldigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcoldigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcoldigo` DEFAULT CHARACTER SET utf8 ;
USE `bdcoldigo` ;

-- -----------------------------------------------------
-- Table `bdcoldigo`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`marcas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigo`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`produtos` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `categoria` TINYINT(1) UNSIGNED NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `capacidade` INT(4) UNSIGNED NOT NULL,
  `valor` DECIMAL(7,2) UNSIGNED NOT NULL,
  `marcas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_marcas_idx` (`marcas_id` ASC) ,
  CONSTRAINT `fk_produtos_marcas`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `bdcoldigo`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigo`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`compras` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigo`.`compras_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`compras_has_produtos` (
  `compras_id` INT UNSIGNED ZEROFILL NOT NULL,
  `produtos_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`compras_id`, `produtos_id`),
  INDEX `fk_compras_has_produtos_produtos1_idx` (`produtos_id` ASC) ,
  INDEX `fk_compras_has_produtos_compras1_idx` (`compras_id` ASC) ,
  CONSTRAINT `fk_compras_has_produtos_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `bdcoldigo`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `bdcoldigo`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
